# Site settings
title: Demo Mediani.js - Antoni Putra
email: akiddcode@gmail.com
description: "Jquery Mediani.js is simple media manager with bootstrap"
baseurl: "/mediani"
url: "http://antoniputra.github.io"
twitter_username: antoni_putra12
github_username:  antoniputra

repository: http://github.com/antoniputra/mediani

# Build settings
markdown: kramdown
